// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/formula-engine/Bold.tsx": () => import("../components/mockups/formula-engine/Bold.tsx"),
  "./components/mockups/formula-engine/Clean.tsx": () => import("../components/mockups/formula-engine/Clean.tsx"),
  "./components/mockups/formula-engine/Dark.tsx": () => import("../components/mockups/formula-engine/Dark.tsx")
};
